"""Round-13 findings, 2026-09-18. Two familiar shapes — the deny-rule wall was
readable but bypassable through shell variable expansion, and an owner write
through a terminal cleared its own approval on the way to the row.

Each test FAILS on the parent commit (`960d84f`) and PASSES after the fix.
"""
from __future__ import annotations

import fnmatch
from pathlib import Path

import pytest

from skillmem import storage as S


@pytest.fixture
def home(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("SKILLMEM_HOME", str(tmp_path))
    monkeypatch.delenv("SKILLMEM_DB", raising=False)
    return tmp_path


def _conn(home: Path, name: str = "memory.db"):
    conn = S.connect(home / name)
    S.init_schema(conn)
    return conn


def _denied(cmd: str) -> bool:
    from skillmem.cli import _OWNER_DENY_RULES

    for rule in _OWNER_DENY_RULES:
        pat = rule[len("Bash("):-1]
        if fnmatch.fnmatchcase(cmd, pat):
            return True
    return False


# --- P1: shell variable expansion hides the verb from the deny rules ----------

def test_deny_rules_catch_env_variable_bypass_of_the_owner_verbs():
    """`V=trust script -qec 'skillmem $V foo' /dev/null` runs `skillmem trust
    foo` after the shell substitutes `$V`, but Claude Code's fnmatch sees the
    literal command line — no `skillmem trust` substring anywhere — and the
    round-13 evidence walked exactly that path. Any command mentioning
    `skillmem` next to a `$` is either using shell substitution to hide a verb
    or is easy to rewrite without one; the four owner verbs are not worth the
    variable indirection."""
    # The reviewer's exact reproductions.
    assert _denied(
        "V=trust script -qec './.venv/bin/skillmem $V injected' /dev/null"
    )
    assert _denied(
        "V=skills-archive script -qec './.venv/bin/skillmem $V injected' /dev/null"
    )
    assert _denied(
        "V=rm script -qec './.venv/bin/skillmem $V injected' /dev/null"
    )
    assert _denied(
        "V=import-vault script -qec './.venv/bin/skillmem $V /tmp/v' /dev/null"
    )
    # Braced variable form (`${V}`).
    assert _denied("V=trust skillmem ${V} foo")
    # Command substitution — the verb is generated by a subshell.
    assert _denied("skillmem $(echo trust) foo")
    assert _denied("skillmem `echo trust` foo")
    # `eval` reading the verb from anywhere.
    assert _denied("eval 'skillmem trust foo'")
    # And an ordinary read with no substitution is still allowed.
    assert not _denied(
        "skillmem write --slug x --title t --body b --kind note"
    )
    assert not _denied("skillmem read something")


# --- P2: owner update through a terminal keeps its own approval ---------------

def test_owner_terminal_update_preserves_the_supplied_approval(home, monkeypatch):
    """A real owner rewriting a record through a pseudo-terminal gets
    `owner_seal=1`, but the UPDATE in `_upsert_update_tx` unconditionally
    reset `trusted_at=NULL, trusted_by=NULL`. The next `briefing()` then
    filed the owner's own rule under `awaiting_reapproval` and dropped it
    from the session preamble until the owner ran a separate `skillmem trust`.
    The write from a terminal IS the approval; storing NULL threw it away.
    """
    conn = _conn(home)
    # An agent writes the first version — no terminal, so no approval.
    monkeypatch.setattr(S, "owner_present", lambda: False)
    S.upsert(
        conn,
        S.MemoryItem(slug="rule", kind="feedback", title="Rule",
                     body="agent-v1: unapproved text",
                     origin="agent"),
        owner_call=False,
    )
    # Owner updates through a terminal, carrying the CLI-minted trust stamp.
    monkeypatch.setattr(S, "owner_present", lambda: True)
    S.upsert(
        conn,
        S.MemoryItem(slug="rule", kind="feedback", title="Rule",
                     body="owner-v2: the words the owner actually approves",
                     origin="owner", trusted_at=1789697840,
                     trusted_by="cli-tty"),
        owner_call=True, reason="owner-edit", force=True,
    )
    row = conn.execute(
        "SELECT body, origin, owner_seal, trusted_at, trusted_by "
        "FROM memory_items WHERE slug='rule'"
    ).fetchone()
    assert row["body"] == "owner-v2: the words the owner actually approves"
    assert row["origin"] == "owner"
    assert row["owner_seal"] == 1
    # The write from a terminal is the approval — the row keeps it.
    assert row["trusted_at"] == 1789697840
    assert row["trusted_by"] == "cli-tty"
    brief = S.briefing(conn, kinds=["feedback"])
    assert not brief.get("awaiting_reapproval"), brief
    # The section carries the owner's rule.
    slugs = [it["slug"] for sec in brief["sections"] for it in sec["items"]]
    assert "rule" in slugs, brief


def test_agent_overwrite_still_clears_trust(home, monkeypatch):
    """The mirror side of the fix: only the owner-at-terminal write carries
    its own approval. An agent overwriting the body still resets trust — the
    approval belonged to the previous words, not to the slug."""
    conn = _conn(home)
    # Owner writes and approves at the terminal.
    monkeypatch.setattr(S, "owner_present", lambda: True)
    S.upsert(
        conn,
        S.MemoryItem(slug="rule", kind="feedback", title="Rule",
                     body="owner-v1: original approved words",
                     origin="owner", trusted_at=1789697000,
                     trusted_by="cli-tty"),
        owner_call=True,
    )
    assert conn.execute(
        "SELECT trusted_at FROM memory_items WHERE slug='rule'"
    ).fetchone()["trusted_at"] == 1789697000
    # Agent overwrites — no terminal.
    monkeypatch.setattr(S, "owner_present", lambda: False)
    S.upsert(
        conn,
        S.MemoryItem(slug="rule", kind="feedback", title="Rule",
                     body="agent-v2: replacement text from an unattended run",
                     origin="agent"),
        owner_call=False, reason="agent-edit", force=True,
    )
    row = conn.execute(
        "SELECT body, origin, owner_seal, trusted_at, trusted_by "
        "FROM memory_items WHERE slug='rule'"
    ).fetchone()
    assert row["body"] == "agent-v2: replacement text from an unattended run"
    # The seal survives an agent overwrite (that is the point of the seal).
    assert row["owner_seal"] == 1
    # But the approval is gone: the words changed and no owner was there.
    assert row["trusted_at"] is None
    assert row["trusted_by"] is None


def test_owner_terminal_same_text_write_applies_the_supplied_approval(
    home, monkeypatch
):
    """The `_upsert_same_text` branch set `owner_seal=1` on an owner write
    but never applied the caller's `trusted_at`/`trusted_by`. So an agent
    writing text T first, then an owner writing the SAME text T at the
    terminal, left the row sealed but unapproved: the CLI-minted stamp went
    straight to the floor. The seal and the approval are the same signal —
    the terminal write applies both."""
    conn = _conn(home)
    # Agent writes first — no terminal, no approval.
    monkeypatch.setattr(S, "owner_present", lambda: False)
    body = "the rule that both sides happen to write with the same words"
    S.upsert(
        conn,
        S.MemoryItem(slug="same", kind="feedback", title="Same",
                     body=body, origin="agent"),
        owner_call=False,
    )
    row = conn.execute(
        "SELECT owner_seal, trusted_at FROM memory_items WHERE slug='same'"
    ).fetchone()
    assert row["owner_seal"] == 0
    assert row["trusted_at"] is None
    # Owner writes identical text at the terminal.
    monkeypatch.setattr(S, "owner_present", lambda: True)
    S.upsert(
        conn,
        S.MemoryItem(slug="same", kind="feedback", title="Same",
                     body=body, origin="owner",
                     trusted_at=1789700000, trusted_by="cli-tty"),
        owner_call=True,
    )
    row = conn.execute(
        "SELECT owner_seal, trusted_at, trusted_by "
        "FROM memory_items WHERE slug='same'"
    ).fetchone()
    assert row["owner_seal"] == 1
    assert row["trusted_at"] == 1789700000
    assert row["trusted_by"] == "cli-tty"

def test_the_owner_signal_is_not_fooled_by_a_null_device():
    """On Windows isatty() is true for any character device, NUL included, so
    `stdin=DEVNULL` from an agent's subprocess looked like a person at a keyboard.
    The console itself has to be asked."""
    import subprocess, sys, textwrap
    probe = textwrap.dedent("""
        import sys
        from skillmem import storage as S
        print("owner" if S.owner_present() else "agent")
    """)
    res = subprocess.run([sys.executable, "-c", probe],
                         stdin=subprocess.DEVNULL, capture_output=True,
                         text=True, timeout=60)
    assert res.stdout.strip() == "agent", (res.stdout, res.stderr)
